
import __ASTRO_IMAGE_IMPORT_Z1FTP1f from "./images/incident-response-checklist.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fincident-response-checklist.md";
import __ASTRO_IMAGE_IMPORT_Z1c14P7 from "./images/introducing-cloud-native-ciso.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fintroducing-cloud-native-ciso.md";
import __ASTRO_IMAGE_IMPORT_2nyX0E from "./images/kubernetes-security-fundamentals.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkubernetes-security-fundamentals.md";
import __ASTRO_IMAGE_IMPORT_Z1ny0Q5 from "./images/minimum-viable-security.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fminimum-viable-security-program.md";
import __ASTRO_IMAGE_IMPORT_1whU7n from "./images/zero-trust-access.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fzero-trust-access-strategies.md";
import __ASTRO_IMAGE_IMPORT_1dSDYd from "./images/threat-modeling-quick-guide.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreat-modeling-quick-guide.md";
import __ASTRO_IMAGE_IMPORT_ZCvUUs from "./images/kubernetes-hardening.png?astroContentImageFlag=&importer=src%2Fcontent%2Fplaybook%2Fkubernetes-hardening.md";
export default new Map([["./images/incident-response-checklist.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fincident-response-checklist.md", __ASTRO_IMAGE_IMPORT_Z1FTP1f], ["./images/introducing-cloud-native-ciso.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fintroducing-cloud-native-ciso.md", __ASTRO_IMAGE_IMPORT_Z1c14P7], ["./images/kubernetes-security-fundamentals.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fkubernetes-security-fundamentals.md", __ASTRO_IMAGE_IMPORT_2nyX0E], ["./images/minimum-viable-security.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fminimum-viable-security-program.md", __ASTRO_IMAGE_IMPORT_Z1ny0Q5], ["./images/zero-trust-access.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fzero-trust-access-strategies.md", __ASTRO_IMAGE_IMPORT_1whU7n], ["./images/threat-modeling-quick-guide.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthreat-modeling-quick-guide.md", __ASTRO_IMAGE_IMPORT_1dSDYd], ["./images/kubernetes-hardening.png?astroContentImageFlag=&importer=src%2Fcontent%2Fplaybook%2Fkubernetes-hardening.md", __ASTRO_IMAGE_IMPORT_ZCvUUs]]);
		