
import __ASTRO_IMAGE_IMPORT_1a5rt4 from "./images/titan-studio-themes.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fabout-titan-studio-themes.md";
import __ASTRO_IMAGE_IMPORT_1AUxWd from "./images/astro-marketing.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fastro-for-marketing-websites.md";
import __ASTRO_IMAGE_IMPORT_Z1O4Yg9 from "./images/building-pages.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-pages.md";
import __ASTRO_IMAGE_IMPORT_lE7oG from "./images/edit-posts.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fedit-posts.md";
import __ASTRO_IMAGE_IMPORT_1DIPRL from "./images/page-speed-seo.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpage-speed-seo-impact.md";
import __ASTRO_IMAGE_IMPORT_GcW10 from "./images/update-categories.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fupdating-categories.md";
import __ASTRO_IMAGE_IMPORT_ZlNA30 from "./images/apollo.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fapollo.md";
import __ASTRO_IMAGE_IMPORT_1JhuqI from "./images/ares.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fares.md";
import __ASTRO_IMAGE_IMPORT_Zkdikg from "./images/artemis.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fartemis.md";
import __ASTRO_IMAGE_IMPORT_EYsW1 from "./images/athena.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fathena.md";
import __ASTRO_IMAGE_IMPORT_1bncN1 from "./images/demeter.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fdemeter.md";
import __ASTRO_IMAGE_IMPORT_1YN60t from "./images/dionysus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fdionysus.md";
import __ASTRO_IMAGE_IMPORT_Z1QCRi5 from "./images/hades.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fhades.md";
import __ASTRO_IMAGE_IMPORT_Zikhq2 from "./images/hermes.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fhermes.md";
import __ASTRO_IMAGE_IMPORT_ZYJv7G from "./images/zeus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fzeus.md";
import __ASTRO_IMAGE_IMPORT_Z7nhfT from "./images/poseidon.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fposeidon.md";
export default new Map([["./images/titan-studio-themes.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fabout-titan-studio-themes.md", __ASTRO_IMAGE_IMPORT_1a5rt4], ["./images/astro-marketing.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fastro-for-marketing-websites.md", __ASTRO_IMAGE_IMPORT_1AUxWd], ["./images/building-pages.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-pages.md", __ASTRO_IMAGE_IMPORT_Z1O4Yg9], ["./images/edit-posts.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fedit-posts.md", __ASTRO_IMAGE_IMPORT_lE7oG], ["./images/page-speed-seo.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpage-speed-seo-impact.md", __ASTRO_IMAGE_IMPORT_1DIPRL], ["./images/update-categories.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fupdating-categories.md", __ASTRO_IMAGE_IMPORT_GcW10], ["./images/apollo.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fapollo.md", __ASTRO_IMAGE_IMPORT_ZlNA30], ["./images/ares.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fares.md", __ASTRO_IMAGE_IMPORT_1JhuqI], ["./images/artemis.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fartemis.md", __ASTRO_IMAGE_IMPORT_Zkdikg], ["./images/athena.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fathena.md", __ASTRO_IMAGE_IMPORT_EYsW1], ["./images/demeter.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fdemeter.md", __ASTRO_IMAGE_IMPORT_1bncN1], ["./images/dionysus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fdionysus.md", __ASTRO_IMAGE_IMPORT_1YN60t], ["./images/hades.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fhades.md", __ASTRO_IMAGE_IMPORT_Z1QCRi5], ["./images/hermes.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fhermes.md", __ASTRO_IMAGE_IMPORT_Zikhq2], ["./images/zeus.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fzeus.md", __ASTRO_IMAGE_IMPORT_ZYJv7G], ["./images/poseidon.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fteam%2Fposeidon.md", __ASTRO_IMAGE_IMPORT_Z7nhfT]]);
		