
import __ASTRO_IMAGE_IMPORT_1a5rt4 from "./images/titan-studio-themes.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fabout-titan-studio-themes.md";
import __ASTRO_IMAGE_IMPORT_1AUxWd from "./images/astro-marketing.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fastro-for-marketing-websites.md";
import __ASTRO_IMAGE_IMPORT_Z1O4Yg9 from "./images/building-pages.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-pages.md";
import __ASTRO_IMAGE_IMPORT_1DIPRL from "./images/page-speed-seo.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpage-speed-seo-impact.md";
import __ASTRO_IMAGE_IMPORT_lE7oG from "./images/edit-posts.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fedit-posts.md";
import __ASTRO_IMAGE_IMPORT_GcW10 from "./images/update-categories.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fupdating-categories.md";
import __ASTRO_IMAGE_IMPORT_ZCvUUs from "./images/kubernetes-hardening.png?astroContentImageFlag=&importer=src%2Fcontent%2Fplaybook%2Fkubernetes-hardening.md";
export default new Map([["./images/titan-studio-themes.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fabout-titan-studio-themes.md", __ASTRO_IMAGE_IMPORT_1a5rt4], ["./images/astro-marketing.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fastro-for-marketing-websites.md", __ASTRO_IMAGE_IMPORT_1AUxWd], ["./images/building-pages.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fbuilding-pages.md", __ASTRO_IMAGE_IMPORT_Z1O4Yg9], ["./images/page-speed-seo.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fpage-speed-seo-impact.md", __ASTRO_IMAGE_IMPORT_1DIPRL], ["./images/edit-posts.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fedit-posts.md", __ASTRO_IMAGE_IMPORT_lE7oG], ["./images/update-categories.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fupdating-categories.md", __ASTRO_IMAGE_IMPORT_GcW10], ["./images/kubernetes-hardening.png?astroContentImageFlag=&importer=src%2Fcontent%2Fplaybook%2Fkubernetes-hardening.md", __ASTRO_IMAGE_IMPORT_ZCvUUs]]);
		